# Generated by Django 3.2.12 on 2022-03-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_auto_20220328_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
